package com.konradrej.rcpc.core.network;

/**
 * Specifies available message types.
 *
 * @author Konrad Rej
 * @author www.konradrej.com
 * @version 1.5
 */
public enum MessageType {
    INFO_CURRENT_VOLUME_UPDATE,
    INFO_USER_ACCEPTED_CONNECTION,
    INFO_USER_CLOSED_CONNECTION,
    INFO_UUID,

    ACTION_INCREASE_VOLUME,
    ACTION_DECREASE_VOLUME,
    ACTION_PREVIOUS_TRACK,
    ACTION_NEXT_TRACK,
    ACTION_PLAY_PAUSE,
    ACTION_STOP,
    ACTION_SET_VOLUME,
    ACTION_PRIMARY_CLICK,
    ACTION_SECONDARY_CLICK,
    ACTION_MIDDLE_CLICK,
    ACTION_SCROLL,
    ACTION_MOVE,
    ACTION_GET_CURRENT_VOLUME,
    ACTION_GET_UUID,
    ACTION_CLICK_AND_DRAG_START,
    ACTION_CLICK_AND_DRAG_MOVE,
    ACTION_CLICK_AND_DRAG_END,

    ERROR_SERVER_BUSY,
    ERROR_USER_ABORTED_CONNECTION,
    ERROR_NOT_IMPLEMENTED_TYPE_SENT
}